---
title: University Major Portfolio
---

During the fall of my junior year, I pitched and was approved for a self-designed University Major in Data & Communication.

The major considers data and rhetoric as two languages of evidence that together influence how contemporary societies understand truth, establish credibility, and motivate collective action. It aims to study communication empirically, examine the communication of data ethically, and to explore how these modes of evidence operate in tandem and shape our perspectives on data, rhetoric, and the social world. 

As part of my assessment for this major, I have developed a portfolio exploring a range of genres and audiences. The following artifacts span everything from survey design to statistical modeling to presentation development to persuasive writing. The goal is to practice writing modes from all three pillars of the major: Data Analysis and Research Methodology, Rhetorical Theory and Writing Praxis, and the Social Psychology of Civic Engagement; and reflect on these interdisciplinary approaches. 




## Included Work
- [Experimental Design Final Project](university-major/change-talk-experiment.qmd)
- [Psychology Seminar on Social Action Op-Ed](university-major/social-action-oped.qmd)
- Data Journalism Term Project
- Tutorial in Rhetoric, Genre, and Discourse Final Project
- Capstone: Academic Write-Up
- Capstone: Public Explainer
- Capstone: Presentation and Oral Defense